spring:
  application:
     name: accounts-service
     
  datasource:
    url: postgres://gxnxiopdsnoqsb:c3f3971858491cb25896a8ab0bf5d00b5f51001977581abd67b0028c4eb2df11@ec2-54-243-137-182.compute-1.amazonaws.com:5432/d5173sl39gerqo
    username: gxnxiopdsnoqsb
    password: c3f3971858491cb25896a8ab0bf5d00b5f51001977581abd67b0028c4eb2df11
  jpa:
    generate-ddl: true
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value} 
   
  client:    
    serviceUrl:
      defaultZone: http://localhost:5002/eureka
    
server:
  port: 0 
  
logging:
  level: 
    httpclient.wire: DEBUG 
    
    
  
 
 
  